// all factions with details

export const factionKeys = [
	"theArborec","theArgentFlight","theBaronyOfLetnev",
	"theClanOfSaar","theCouncilKeleres","theCrimsonRebellion",
	"theDeepwroughtScholarate","theEmbersOfMuaat","theEmiratesOfHacan",
	"theEmpyrean","theFederationOfSol","theFirmamentTheObsidian",
	"lastBastion","theGhostsOfCreuss","theL1Z1XMindnet",
	"theMahactGeneSorcerers","theMentakCoalition","theNaaluCollective",
	"theNaazRokhaAlliance","theNekroVirus","theNomad",
	"theRalNelConsortium","sardakkNorr","theTitansOfUl",
	"theUniversitiesOfJolNar","theVuilRaithCabal","theWinnu",
	"theXxchaKingdom","theYinBrotherhood","theYssarilTribes"
];

export const factions = {
	theArborec:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theArgentFlight:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theBaronyOfLetnev:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theClanOfSaar:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theCouncilKeleres:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theCrimsonRebellion:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theDeepwroughtScholarate:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theEmbersOfMuaat:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theEmiratesOfHacan:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theEmpyrean:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theFederationOfSol:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theFirmamentTheObsidian:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	lastBastion:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theGhostsOfCreuss:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theL1Z1XMindnet:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theMahactGeneSorcerers:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theMentakCoalition:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theNaaluCollective:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theNaazRokhaAlliance:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theNekroVirus:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theNomad:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theRalNelConsortium:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	sardakkNorr:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theTitansOfUl:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theUniversitiesOfJolNar:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theVuilRaithCabal:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theWinnu:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theXxchaKingdom:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theYinBrotherhood:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	},
	theYssarilTribes:{
		name:"",
		expansion:"Base Game",
		startingUnits:{},
		startingTechnologies:{},
		startingPlanets:{},
		commodities:"",
		complexity:"",
		abilities:{},
		promissory:{},
		technologies:{},
		breakthrough:{},
		leaders:{
			agent:{
				name:"",
				unlock:"",
				ability:""
			},
			commander:{},
			hero:{}
		},
		units:{
			flagship:{
				name:"",
				type:"Ship",
				cost:"8",
				combat:"",
				move:"",
				capacity:"",
				abilities:["Sustain Damage"]
			},
			mech:{
				name:"Mech",
				type:"Ground Unit",
				cost:"2",
				combat:"6",
				move:"-",
				capacity:"-",
				abilities:["Sustain Damage"],
				reinforcements:"4"
			},
			replacement:{
				name:"",
				type:"",
				cost:"",
				combat:"",
				move:"",
				capacity:"",
				abilities:[],
				upgrade:{
					prereq:"",
					name:"",
					type:"",
					cost:"",
					combat:"",
					move:"",
					capacity:"",
					abilities:[]
				},
				reinforcements:""
			}
		}
	}
};
